apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-mon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-mon
  template:
    metadata:
      labels:
        app: aws-mon
    spec:
      containers:
      - name: aws-monitor-flask
        image: madaralmog/flask-aws-monitor:latest
        ports:
        - containerPort: 5001
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_SECRET_ACCESS_KEY